###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: symfony-redis

    mysql:
      image: mysql:8.0
      container_name: symfony-mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=sanane123
        - MYSQL_DATABASE=docker
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=sanane123

    webserver:
      image: nginx:alpine
      container_name: symfony-webserver
      working_dir: /var/www/html
      volumes:
          - ./application:/var/www/html
          - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: docker/php-fpm
      container_name: symfony-php-fpm
      working_dir: /var/www/html
      volumes:
        - ./application:/var/www/html
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini

